#pragma once

#define MOVE_RATIO_PURPLE (0.3)												// segundos que demora cada monstruo en pasar de bloque
#define VEL_PURPLE (BLOCK_SIZE/(FPS*MOVE_RATIO_PURPLE))						// pixeles que recorreran por refresco de pantalla
#define MOVE_RATIO_FATTY (0.3)
#define VEL_FATTY (BLOCK_SIZE/(FPS*MOVE_RATIO_FATTY))
#define MOVE_RATIO_CRAZY (0.2)
#define VEL_CRAZY (BLOCK_SIZE/(FPS*MOVE_RATIO_CRAZY))

#define WALKING_PICS_PURPLE 8
#define WALKING_PICS_FATTY 8
#define WALKING_PICS_CRAZY 8
#define JUMPING_PICS_PURPLE 8
#define JUMPING_PICS_FATTY 1
#define JUMPING_PICS_CRAZY 1
#define ATTACKING_PICS_PURPLE 8
#define ATTACKING_PICS_FATTY 8
#define ATTACKING_PICS_CRAZY 8
#define TRAPPED_PICS_PURPLE 8
#define TRAPPED_PICS_FATTY	8
#define TRAPPED_PICS_CRAZY	8
#define IDLE_PICS_PURPLE	12
#define IDLE_PICS_FATTY		8
#define IDLE_PICS_CRAZY		8
#define FALLING_PICS_PURPLE	8
#define FALLING_PICS_FATTY	1
#define FALLING_PICS_CRAZY	1
#define DYING_PICS_PURPLE	8
#define DYING_PICS_FATTY	8
#define DYING_PICS_CRAZY	8


#define FOLDER_ENEMY	("enemies")
#define FOLDER_PURPLE	("PURPLE")
#define FOLDER_FATTY	("FATTY")
#define FOLDER_CRAZY	("CRAZY")

#define FOLDER_WALKING	("WALKING")		
#define FOLDER_JUMPING	("JUMPING")
#define FOLDER_IDLE		("IDLE")
#define FOLDER_TRAPPED	("TRAPPED")
#define FOLDER_ATTACKING	("ATTACKING")
#define FOLDER_FALLING		("FALLING")
#define FOLDER_DYING		("DYING")

#define FILE_PURPLE_WALKING	("__Bandit02_Walk_00")
#define FILE_PURPLE_JUMPING	("__Bandit02_JumpUP_00")
#define FILE_PURPLE_ATTACKING	("__Bandit02_Attack_00")
#define FILE_PURPLE_TRAPPED	("__Bandit02_Hurt_00")
#define FILE_PURPLE_IDLE	("__Bandit02_Idle_00")
#define FILE_PURPLE_FALLING	("__Bandit02_FallDown_00")
#define FILE_PURPLE_DYING	("__Bandit02_Die_00")

#define FILE_FATTY_WALKING	("2D_GOBLIN__Run_00")
#define FILE_FATTY_JUMPING	("2D_GOBLIN__Jump_Up_00")
#define FILE_FATTY_ATTACKING	("2D_GOBLIN__Attack_00")
#define FILE_FATTY_TRAPPED	("2D_GOBLIN__Hurt_00")
#define FILE_FATTY_IDLE		("2D_GOBLIN__Idle_Blinking_00")
#define FILE_FATTY_FALLING	("2D_GOBLIN__Fall_Down_00")
#define FILE_FATTY_DYING	("2D_GOBLIN__Die_00")

#define FILE_CRAZY_WALKING	("2D_SM02_Run_00")
#define FILE_CRAZY_JUMPING	("2D_SM02_JumpUp_00")
#define FILE_CRAZY_ATTACKING	("2D_SM02_Attack_00")
#define FILE_CRAZY_TRAPPED	("2D_SM02_Hurt_00")
#define FILE_CRAZY_IDLE		("2D_SM02_Idle_00")
#define FILE_CRAZY_FALLING	("2D_SM02_FallDown_00")
#define FILE_CRAZY_DYING	("2D_SM02_Die_00")